version: '3.8'
services:
  master-service:
    ports:
        - "9092:8000"
    build:
        context: "."
        network: host
        dockerfile: "./Dockerfile"
    command: 'php artisan serve --host=0.0.0.0'
    depends_on:
      - master-service-db
    volumes:
      - ./:/var/www
  master-service-db:
    build:
      network: host
    ports:
        - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=master
    image: mysql:8.0.29
